apiVersion: v1
kind: Pod
metadata:
  name: mc2
spec:
  containers:
  - name: consumer
    image: bernardovale/ch6_ipc
    imagePullPolicy: Always
    command: ["/usr/bin/ipc", "-consumer"]
  - name: producer
    image: bernardovale/ch6_ipc
    imagePullPolicy: Always
    command: ["/usr/bin/ipc", "-producer"]
  restartPolicy: Never