apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: hello-color-app
  labels:
    app: hello-color
    track: stable
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-color
      track: stable
  template:
    metadata:
      labels:
        app: hello-color
        track: stable
    spec:
      containers:
      - name: hello-k8s
        image: bernardovale/hello-k8s:blue
        imagePullPolicy: Always
        env:
        - name: APP_ENV
          value: Production
        ports:
        - containerPort: 8001