apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: slow-app
  labels:
    app: slow
    track: stable
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slow
  template:
    metadata:
      labels:
        app: slow
    spec:
      containers:
      - name: hello-k8s
        image: appuio/example-spring-boot
        imagePullPolicy: Always
        ports:
        - containerPort: 8080