apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: slow-app
  labels:
    app: slow
    track: stable
spec:
  replicas: 4
  selector:
    matchLabels:
      app: slow
  template:
    metadata:
      labels:
        app: slow
    spec:
      containers:
      - name: hello-k8s
        image: appuio/example-spring-boot
        readinessProbe:
          httpGet:
            path: /pod
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 1
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /pod
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080