kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: example-dynamic-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: example-dynamic-pvc