kind: PersistentVolume
apiVersion: v1
metadata:
  name: example-pv
  labels:
    type: amazonEBS
    name: example-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-04703acedc5c14624
    fsType: ext4