apiVersion: v1
kind: Pod
metadata:
  name: pod-with-secrets
spec:
  containers:
  - name: secret-pod
    image: nginx
    volumeMounts:
    - name: secret-config
      mountPath: "/etc/config"
    envFrom:
      - secretRef:
          name: envs-secret
  volumes:
  - name: secret-config
    secret:
      secretName: my-dirty-little-secret